---
project_dir: /opt/wordpress
project_name: wpstack
wp_http_port: 8080

mysql_image: "mysql:5.7"
mysql_root_password: "rootpass123"
mysql_db_name: "wordpress"
mysql_user: "wp_user"
mysql_password: "wp_pass123"
mysql_repl_user: "repl_user"
mysql_repl_password: "repl_pass123"
mysql_repl_connect_retry: 5
mysql_exporter_user: "exporter"
mysql_exporter_password: "exporter_pass123"

wordpress_image: "wordpress:6.5.5-php8.1-apache"

mysql_master_port_host: 3306
mysql_slave_port_host: 3307
prometheus_port: 9090
prometheus_retention: 3d
grafana_port: 3000
grafana_admin_user: admin
grafana_admin_password: "admin_pass123"
monitoring_url: "http://{{ ansible_host | default(inventory_hostname) }}:{{ grafana_port }}"
