- name: Deploy WP with MariaDB primary-replica
  hosts: carrier
  gather_facts: true
  become: true

  pre_tasks:
    - name: Target
      ansible.builtin.debug:
        msg: "Target {{ inventory_hostname }} {{ ansible_host }}"

  roles:
    - role: docker
      tags: ['docker']
    - role: network
      tags: ['network']
    - role: db_cluster
      tags: ['db']

  tasks:
    - name: Ensure WP is deployed after DB cluster
      ansible.builtin.include_role:
        name: wordpress
      tags: ['wp']

    - name: HTTP check WordPress
      ansible.builtin.uri:
        url: "http://{{ hostvars[inventory_hostname].ansible_host | default(inventory_hostname) }}:{{ wordpress_port }}/wp-admin/install.php"
        status_code: 200,301,302
        return_content: false
      register: wp_http
      until: wp_http.status in [200, 301, 302]
      retries: 10
      delay: 3
      tags: ['wp']
