- name: Deploy WP with external DB
  hosts: carrier
  gather_facts: true
  become: true

  vars:
    db_container_name: wp-db
    db_volume: db_data
    db_image: mariadb:10.11
    wordpress_db_host: "{{ db_container_name }}"
    wordpress_db_port: 3306

  roles:
    - role: db
    - role: wordpress
