- name: Ensure DB volume
  community.docker.docker_volume:
    name: "{{ db_volume }}"
    state: present

- name: Run MariaDB container
  community.docker.docker_container:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    volumes:
      - "{{ db_volume }}:/var/lib/mysql"
    env:
      MARIADB_ROOT_PASSWORD: "{{ db_root_password }}"
      MARIADB_DATABASE: "{{ wordpress_db_name }}"
      MARIADB_USER: "{{ wordpress_db_user }}"
      MARIADB_PASSWORD: "{{ wordpress_db_password }}"
      MARIADB_CHARSET: "{{ db_charset }}"
      MARIADB_COLLATE: "{{ db_collation }}"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p{{ db_root_password }} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
