docker_network_name: wp_network

# Контейнеры БД
db_cluster_primary_container_name: mysql_master
db_cluster_replica_container_name: mysql_replica

# Порты и volume
db_cluster_primary_port: 3306
db_cluster_replica_port: 3307
db_cluster_primary_bind: "{{ db_cluster_primary_port }}:3306"
db_cluster_replica_bind: "{{ db_cluster_replica_port }}:3306"
db_primary_volume: mysql_master_data
db_replica_volume: mysql_replica_data

# Образы
db_image: mysql:5.7
wordpress_image: wordpress:6.6-apache

# WordPress
wordpress_container_name: wordpress
wordpress_volume: wordpress_data
wordpress_port: 8080
wp_db_user: wpuser
wp_db_password: wp_local_dev_please_change
wp_db_name: wpdb
wordpress_db_user: "{{ wp_db_user }}"
wordpress_db_password: "{{ wp_db_password }}"
wordpress_db_name: "{{ wp_db_name }}"
wordpress_db_host: "{{ db_cluster_primary_container_name }}"
wordpress_db_port: "{{ db_cluster_primary_port }}"

# Секреты
mysql_root_password: root_local_dev_please_change
db_cluster_repl_user: replicator
db_cluster_repl_password: repl_local_dev_please_change

# GTID-конфиги
mysql_master_cnf:
  - "bind-address=0.0.0.0"
  - "server-id=1"
  - "expire_logs_days=7"
  - "log_bin=/var/lib/mysql/mysql-bin"
  - "binlog_format=ROW"
  - "explicit_defaults_for_timestamp=1"
  - "gtid_mode=ON"
  - "enforce_gtid_consistency=ON"

mysql_replica_cnf:
  - "bind-address=0.0.0.0"
  - "server-id=2"
  - "relay_log=relay-bin"
  - "relay_log_index=relay-bin.index"
  - "gtid_mode=ON"
  - "enforce_gtid_consistency=ON"
  - "log_slave_updates=ON"
  - "read_only=ON"

# Миграция из single DB
legacy_db_container_name: wp-db
migrate_from_legacy: true
