docker_network_name: wpnet

db_image: mariadb:10.11
db_container_name: wp-db
db_volume: db_data
db_port: 3306
db_charset: utf8mb4

wordpress_port: 8080
wordpress_db_user: wpuser
wordpress_db_password: itmokirill
wordpress_db_name: wpdb

db_host: "{{ db_container_name }}"
wordpress_db_host: "{{ db_host }}"
wordpress_db_port: "{{ db_port }}"

db_cluster_primary_container_name: wp-db-primary
db_cluster_replica_container_name: wp-db-replica
db_cluster_primary_volume: db_primary_data
db_cluster_replica_volume: db_replica_data
db_cluster_primary_port: 3306
db_cluster_replica_port: 3307

db_cluster_mysql_login_user: root
db_cluster_mysql_login_host_primary: 127.0.0.1
db_cluster_mysql_login_port_primary: 3306
db_cluster_mysql_login_host_replica: 127.0.0.1
db_cluster_mysql_login_port_replica: 3307

db_cluster_repl_user: repl

db_repl_user: "{{ db_cluster_repl_user }}"
db_repl_password: "{{ db_cluster_repl_password | default(vault_db_cluster_repl_password | default(omit)) }}"
